// todoapp-react/src/components/todos/Todos.jsx
import React, { useState, Component } from "react";
import { TodoFooter } from "../todo-footer/TodoFooter";
import { TodoHeader } from "../todo-header/TodoHeader";
import { TodoList } from "../todo-list/TodoList";
import "./Todos.css";

// react hooks introduced in 16.8v
// useState, useEffect, useCallback, useLayoutEffect, useReducer, useRef, useId

export const Todos = () => {
  const [todos, setTodos] = useState([]);
  const [completed, setCompleted] = useState(0);

  const addTodo = (newTodo) => {
    if (newTodo.trim().length === 0) return false;
    const updatedTodos = [
      ...todos,
      { id: todos.length + 1, todo: newTodo, isCompleted: false },
    ];
    setTodos(updatedTodos);
    calCompletedTodos(updatedTodos);
  };

  const calCompletedTodos = (t) => {
    const completed = t.filter((todo) => todo.isCompleted);
    setCompleted(completed.length);
  };

  return (
    <div className="container app-todos">
      <TodoHeader handleSubmit={addTodo} />
      <TodoList todos={todos} />
      <TodoFooter total={todos.length} completed={completed} />
    </div>
  );
};

/**
 * Phase I Mounting -> invoked only once
 * constructor
 * static getDerivedStateFromProps
 * render
 * componentDidMount
 * Phase II Updating
 * static getDerivedStateFromProps
 * shouldComponentUpdate
 * render
 * static getSnapshotBeforeUpdate
 * componentDidUpdate
 * Phase III Unmounting ->  invoked only once
 * componentWillUnmount
 */
export class TodosComponent extends Component {
  constructor(props) {
    super(props);
    this.appTitle = "Todos";
    this.state = {
      title: "Todos",
      todos: ["Learn HTML"],
    };
    // this.handleClick = this.handleClick.bind(this);
  }

  handleClick = () => {
    this.setState({ title: "Todos updated" });
  };

  render() {
    return (
      <div className="container">
        <h2 title={this.state.title}>
          {this.state.title} || {this.appTitle}
        </h2>
        <button onClick={this.handleClick}>Click Me</button>
      </div>
    );
  }
}

// todoapp/src/app/todo/todos/todos.component.ts
import { Component, OnInit } from '@angular/core';

import { Todo } from '../models/todo.class';

@Component({
  selector: 'app-todos',
  templateUrl: './todos.component.html',
  styleUrls: ['./todos.component.css'],
})
export class TodosComponent implements OnInit {
  public appTitle: string = 'Todos';
  public todos: Todo[] = [
    new Todo(1, 'Learn HTML', true),
    new Todo(2, 'Learn CSS', true),
    new Todo(3, 'Learn Javascript', false),
    new Todo(4, 'Learn ES6', true),
    new Todo(5, 'Learn Angular', false),
    new Todo(6, 'Learn React', false),
  ];
  public completed: number = 0;

  constructor() {}

  ngOnInit(): void {
    this.calculateCompletedTodos();
  }

  handleAddTodo(newTodo: string) {
    if(newTodo.trim().length === 0) {
      return;
    }
    this.todos.push(new Todo(this.todos.length + 1, newTodo))
    this.calculateCompletedTodos();
  }

  calculateCompletedTodos() {
    const completedTodos = this.todos.filter(todo => todo.isCompleted);
    this.completed = completedTodos.length;
  }
}

<div
  class="app-todos"
>
  <app-todo-header
    [appTitle]="appTitle"
    (addTodo)="handleAddTodo($event)"
  ></app-todo-header>
  <app-todo-list [todos]="todos"></app-todo-list>
  <app-todo-footer [total]="todos.length" [completed]="completed"></app-todo-footer>
</div>
