// todoapp/src/app/todo/todo-item/todo-item.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { Todo } from '../models/todo.class';

@Component({
  selector: 'app-todo-item',
  templateUrl: './todo-item.component.html',
  styleUrls: ['./todo-item.component.css'],
})
export class TodoItemComponent implements OnInit {
  @Input('todo') todo?: Todo;
  @Input('isDetail') isDetail?: boolean;
  @Output('editTodo') editTodo: EventEmitter<number> = new EventEmitter();
  @Output('deleteTodo') deleteTodo: EventEmitter<number> = new EventEmitter();

  constructor() {}

  ngOnInit(): void {}

  handleEditTodo() {}
  handleDeleteTodo() {}
}

<div *ngIf="todo" class="todo">
  <label class="todo-toggle" [for]="todo.id">
    <input type="checkbox" name="todo-toggle" [id]="todo.id">
    {{todo.todo }}
  </label>
  <div class="todo-actions">
    <a class="button button-icon" [routerLink]="['/todos', todo.id]" *ngIf="!isDetail">Detail</a>
    <button class="button button-icon button-info" (click)="handleEditTodo()">Edit</button>
    <button class="button button-icon button-danger" (click)="handleDeleteTodo()">Del</button>
  </div>
</div>

// todoapp-react/src/components/todo-item/TodoItem.jsx
import React from "react";

export const TodoItem = ({ todo }) => {
  return (
    <li className="todos-item">
      <label htmlFor="">
        <input type="checkbox" name="todo-toggle" className="todo-toggle" />
        {todo.todo}
      </label>
      <div className="todos-actions">
        <button className="button button-icon button-default">Detail</button>
        <button className="button button-icon button-info">Edit</button>
        <button className="button button-icon button-danger">Delete</button>
      </div>
    </li>
  );
}
