// todoapp/src/app/auth/signin/signin.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import {
  FormGroup,
  FormBuilder,
  Validators,
} from '@angular/forms';

import { AuthService } from '../auth.service';

@Component({
  selector: 'app-signin',
  templateUrl: './signin.component.html',
  styleUrls: ['./signin.component.css'],
})
export class SigninComponent implements OnInit {
  public userForm: FormGroup;

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) {
    this.userForm = this.fb.group({
      email: ['', [Validators.email, Validators.required]],
      password: ['', [Validators.required, Validators.minLength(8)]],
    });
  }

  ngOnInit(): void {}

  handleLogin() {
    if (this.userForm.invalid) {
      return;
    }
    this.authService.login(this.userForm.value).subscribe((res) => {
      this.authService.setAccessToken(res.accessToken);
      localStorage.setItem('accessToken', res.accessToken);
      localStorage.setItem('user', JSON.stringify(res.user));
      this.userForm.reset();
      this.router.navigateByUrl('/todos');
    });
  }
}

<div class="app-auth app-signin">
  <form class="form-signin" (ngSubmit)="handleLogin()" [formGroup]="userForm">
    <div class="form-group">
      <label
        for="username"
        class="sr-only"
      >Enter your register email</label>
      <input
        type="email"
        id="username"
        name="username"
        class="form-input"
        placeholder="Here your email"
        autocomplete="username"
        formControlName="email"
      >
    </div>
    <div class="form-group">
      <label
        for="password"
        class="sr-only"
      >Enter your password</label>
      <input
        type="password"
        id="password"
        name="password"
        class="form-input"
        placeholder="Here your password"
        autocomplete="current-password"
        formControlName="password"
      >
    </div>
    <div class="form-group text-center">
      <button
        type="submit"
        class="button"
        [disabled]="userForm.invalid"
      >Login</button>
    </div>
    <div class="form-group"><span>Don't have an account <a
          type="button"
          class="button"
          routerLink="/auth/register"
        >Register</a></span></div>
  </form>
</div>

// todoapp-react/src/components/signin/Signin.jsx
import React from "react";
import { Link } from "react-router-dom";

export const Signin = () => {
  return (
    <div className="app-auth app-signin">
      <h2 className="auth-title">Welcome back! Login and start creating Todos</h2>
      <form className="form-signin" data-test-id="loginForm">
        <div className="form-group">
          <label for="username" className="sr-only">
            Enter your register email
          </label>
          <input
            type="email"
            id="username"
            name="username"
            className="form-input"
            placeholder="Here your email"
            autocomplete="username"
          />
        </div>
        <div className="form-group">
          <label for="password" className="sr-only">
            Enter your password
          </label>
          <input
            type="password"
            id="password"
            name="password"
            className="form-input"
            placeholder="Here your password"
            autocomplete="current-password"
          />
        </div>
        <div className="form-group text-center">
          <button type="submit" className="button" data-test-id="loginBtn">
            Login
          </button>
        </div>
        <div className="form-group">
          <span>
            Don't have an account{" "}
            <Link
              type="button"
              className="button button-link"
              to={"/auth/register"}
            >
              Register
            </Link>
          </span>
        </div>
      </form>
    </div>
  );
};
