// todoapp/src/app/auth/signup/signup.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, FormBuilder, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../auth.service';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css'],
})
export class SignupComponent implements OnInit {
  public userForm: FormGroup;
  /* 
  public username: FormControl = new FormControl('', [
    Validators.email,
    Validators.required,
  ]);
  public password: FormControl = new FormControl('', [
    Validators.required,
    Validators.minLength(8),
  ]);
  public userForm: FormGroup = new FormGroup({
    usernameUF: new FormControl('', [Validators.email, Validators.required]),
    passwordUF: new FormControl('', [
      Validators.required,
      Validators.minLength(8),
    ]),
  }); */

  constructor(private fb: FormBuilder, private authService: AuthService, private router: Router) {
    this.userForm = this.fb.group({
      email: ['', [Validators.email, Validators.required]],
      password: ['', [Validators.required, Validators.minLength(8)]],
    });
  }

  ngOnInit(): void {}

  handleRegister() {
    if(this.userForm.invalid) {
      return;
    }
    this.authService.register(this.userForm.value).subscribe((res) => {
      this.authService.setAccessToken(res.accessToken);
      localStorage.setItem('accessToken', res.accessToken);
      localStorage.setItem('user', JSON.stringify(res.user));
      this.userForm.reset();
      this.router.navigateByUrl('/todos');
    })
  }
}

<div class="app-auth app-signup">
  <form class="form-signup" (ngSubmit)="handleRegister()" [formGroup]="userForm" data-test-id="signupForm">
    <div class="form-group">
      <label for="username" class="sr-only">Enter your email</label>
      <input type="email" id="username" name="username" class="form-input" placeholder="Here your email" autocomplete="username" formControlName="email">
      <small class="form-error" *ngIf="userForm.get('email')?.dirty && userForm.get('email')?.errors">
        Username is required, Username should be a valid email
      </small>
    </div>
    <div class="form-group">
      <label for="password" class="sr-only">Create a password</label>
      <input type="password" id="password" name="password" class="form-input" placeholder="Here your password" autocomplete="current-password" formControlName="password">
    </div>
    <div class="form-group text-center">
      <button data-test-id="registerBtn" type="submit" class="button" [disabled]="userForm.invalid">Register</button>
    </div>
    <div class="form-group"><span>Already have an account <a type="button" class="button" routerLink="/auth/login">Login</a></span></div>
  </form>
</div>

// todoapp-react/src/components/signup/Signup.jsx
import React from "react";
import { Link } from "react-router-dom";

export const Signup = () => {
  return (
    <div className="app-auth app-signup">
      <h2 className="auth-title">Create an account and start using the Todo app</h2>
      <form className="form-signup" data-test-id="signupForm">
        <div className="form-group">
          <label for="username" className="sr-only">
            Enter your email
          </label>
          <input
            type="email"
            id="username"
            name="username"
            className="form-input"
            placeholder="Here your email"
            autocomplete="username"
          />
        </div>
        <div className="form-group">
          <label for="password" className="sr-only">
            Create a password
          </label>
          <input
            type="password"
            id="password"
            name="password"
            className="form-input"
            placeholder="Here your password"
            autocomplete="current-password"
          />
        </div>
        <div className="form-group text-center">
          <button data-test-id="registerBtn" type="submit" className="button">
            Register
          </button>
        </div>
        <div className="form-group">
          <span>
            Already have an account{" "}
            <Link type="button" className="button button-link" to={'/auth/login'}>
              Login
            </Link>
          </span>
        </div>
      </form>
    </div>
  );
};
